name: CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
      - refs/tags/*
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        if: startsWith(github.ref, 'refs/tags')
      - uses: actions/setup-node@v3
        if: startsWith(github.ref, 'refs/tags')
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - run: yarn install --frozen-lockfile
        if: startsWith(github.ref, 'refs/tags')
      - run: yarn build
        if: startsWith(github.ref, 'refs/tags')
      - run: npm publish
        if: startsWith(github.ref, 'refs/tags')
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_API_TOKEN }}
